spring.application.name=api-personas

# R2DBC Configuration
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/apipersonas_db
spring.r2dbc.username=root
spring.r2dbc.password=password

# Inicializacion de base de datos
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# Logging
logging.level.org.springframework.r2dbc=DEBUG
